name: ml_knn
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - scikit-learn=1.1.1
  - pandas=1.4.3
  - numpy=1.23.1
  - matplotlib=3.5.2
  - pandas-profiling=3.2.0
  - ipykernel=6.9.1
  - notebook=6.4.12
  - ipywidgets=7.7.1
  - scipy=1.9.0
  - seaborn=0.11.2
